# Generated by Django 5.2.5 on 2025-08-09 16:28

from django.db import migrations


def update_store_lite_to_markethub(apps, schema_editor):
    """
    Update existing "Store Lite" references to "Markethub" in the database.
    Uses raw SQL for maximum compatibility and safety.
    """
    with schema_editor.connection.cursor() as cursor:
        # Update homepage_heroslide table
        cursor.execute("""
            UPDATE homepage_heroslide 
            SET title = REPLACE(REPLACE(title, 'Store Lite', 'Markethub'), 'store lite', 'Markethub')
            WHERE LOWER(title) LIKE '%store lite%';
        """)
        
        cursor.execute("""
            UPDATE homepage_heroslide 
            SET subtitle = REPLACE(REPLACE(subtitle, 'Store Lite', 'Markethub'), 'store lite', 'Markethub')
            WHERE LOWER(subtitle) LIKE '%store lite%';
        """)
        
        # Update homepage_product table
        cursor.execute("""
            UPDATE homepage_product 
            SET name = REPLACE(REPLACE(name, 'Store Lite', 'Markethub'), 'store lite', 'Markethub')
            WHERE LOWER(name) LIKE '%store lite%';
        """)
        
        cursor.execute("""
            UPDATE homepage_product 
            SET description = REPLACE(REPLACE(description, 'Store Lite', 'Markethub'), 'store lite', 'Markethub')
            WHERE LOWER(description) LIKE '%store lite%';
        """)
        
        # Update homepage_category table
        cursor.execute("""
            UPDATE homepage_category 
            SET name = REPLACE(REPLACE(name, 'Store Lite', 'Markethub'), 'store lite', 'Markethub')
            WHERE LOWER(name) LIKE '%store lite%';
        """)
        
        cursor.execute("""
            UPDATE homepage_category 
            SET description = REPLACE(REPLACE(description, 'Store Lite', 'Markethub'), 'store lite', 'Markethub')
            WHERE LOWER(description) LIKE '%store lite%';
        """)
        
        # Update homepage_promotion table
        cursor.execute("""
            UPDATE homepage_promotion 
            SET title = REPLACE(REPLACE(title, 'Store Lite', 'Markethub'), 'store lite', 'Markethub')
            WHERE LOWER(title) LIKE '%store lite%';
        """)
        
        cursor.execute("""
            UPDATE homepage_promotion 
            SET text = REPLACE(REPLACE(text, 'Store Lite', 'Markethub'), 'store lite', 'Markethub')
            WHERE LOWER(text) LIKE '%store lite%';
        """)


def reverse_update_markethub_to_store_lite(apps, schema_editor):
    """
    Reverse migration: Update "Markethub" back to "Store Lite".
    This is for rollback purposes only.
    """
    with schema_editor.connection.cursor() as cursor:
        # Reverse homepage_heroslide table
        cursor.execute("""
            UPDATE homepage_heroslide 
            SET title = REPLACE(title, 'Markethub', 'Store Lite')
            WHERE LOWER(title) LIKE '%markethub%';
        """)
        
        cursor.execute("""
            UPDATE homepage_heroslide 
            SET subtitle = REPLACE(subtitle, 'Markethub', 'Store Lite')
            WHERE LOWER(subtitle) LIKE '%markethub%';
        """)
        
        # Reverse homepage_product table
        cursor.execute("""
            UPDATE homepage_product 
            SET name = REPLACE(name, 'Markethub', 'Store Lite')
            WHERE LOWER(name) LIKE '%markethub%';
        """)
        
        cursor.execute("""
            UPDATE homepage_product 
            SET description = REPLACE(description, 'Markethub', 'Store Lite')
            WHERE LOWER(description) LIKE '%markethub%';
        """)
        
        # Reverse homepage_category table
        cursor.execute("""
            UPDATE homepage_category 
            SET name = REPLACE(name, 'Markethub', 'Store Lite')
            WHERE LOWER(name) LIKE '%markethub%';
        """)
        
        cursor.execute("""
            UPDATE homepage_category 
            SET description = REPLACE(description, 'Markethub', 'Store Lite')
            WHERE LOWER(description) LIKE '%markethub%';
        """)
        
        # Reverse homepage_promotion table
        cursor.execute("""
            UPDATE homepage_promotion 
            SET title = REPLACE(title, 'Markethub', 'Store Lite')
            WHERE LOWER(title) LIKE '%markethub%';
        """)
        
        cursor.execute("""
            UPDATE homepage_promotion 
            SET text = REPLACE(text, 'Markethub', 'Store Lite')
            WHERE LOWER(text) LIKE '%markethub%';
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            update_store_lite_to_markethub,
            reverse_update_markethub_to_store_lite,
            hints={'homepage': ['HeroSlide', 'Product', 'Category', 'Promotion']}
        ),
    ]
