# Generated by Django 5.2.5 on 2025-08-17 19:22

import django.db.models.deletion
import homepage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_add_stripe_fields_to_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_type', models.CharField(choices=[('id', 'South African ID Document'), ('passport', 'Passport')], help_text='Choose between South African ID or Passport', max_length=10)),
                ('id_number', models.CharField(blank=True, help_text='ID or Passport number', max_length=50)),
                ('id_image_front', models.ImageField(blank=True, help_text='Upload front side of ID or passport photo page', null=True, upload_to=homepage.models.user_id_upload_path)),
                ('id_image_back', models.ImageField(blank=True, help_text='Upload back side of ID (not required for passport)', null=True, upload_to=homepage.models.user_id_upload_path)),
                ('id_verified', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Document Uploaded'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('appealing', 'Under Appeal')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Internal notes for verification')),
                ('extracted_name', models.CharField(blank=True, max_length=200)),
                ('extracted_id_number', models.CharField(blank=True, max_length=50)),
                ('extracted_date_of_birth', models.DateField(blank=True, null=True)),
                ('extracted_address', models.TextField(blank=True)),
                ('ocr_raw_data', models.JSONField(blank=True, default=dict)),
                ('id_hash_front', models.CharField(blank=True, help_text='SHA-256 hash of front image', max_length=64)),
                ('id_hash_back', models.CharField(blank=True, help_text='SHA-256 hash of back image', max_length=64)),
                ('upload_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('upload_user_agent', models.TextField(blank=True)),
                ('id_expires_at', models.DateTimeField(blank=True, help_text='When the ID/passport expires', null=True)),
                ('verification_expires_at', models.DateTimeField(blank=True, help_text='When verification expires', null=True)),
                ('last_verification_check', models.DateTimeField(auto_now=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('is_approved_user', models.BooleanField(default=False, help_text='User approved for platform access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'homepage_userprofile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'ID/Passport Uploaded'), ('auto_verify', 'Automatic Verification'), ('manual_review', 'Manual Review'), ('approve', 'Approved'), ('reject', 'Rejected'), ('appeal', 'Appeal Submitted'), ('reupload', 'ID Re-uploaded'), ('expire', 'Verification Expired'), ('delete', 'Data Deleted')], max_length=50)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Error')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='homepage.userverificationprofile')),
            ],
            options={
                'verbose_name': 'User Verification Log',
                'verbose_name_plural': 'User Verification Logs',
                'db_table': 'homepage_userverificationlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVerificationAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for the appeal')),
                ('additional_documents', models.FileField(blank=True, help_text='Optional additional documentation', null=True, upload_to='user_appeal_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Appeal Approved'), ('denied', 'Appeal Denied'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='homepage.userverificationprofile')),
            ],
            options={
                'verbose_name': 'User Verification Appeal',
                'verbose_name_plural': 'User Verification Appeals',
                'db_table': 'homepage_userverificationappeal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userverificationprofile',
            index=models.Index(fields=['id_verified'], name='homepage_us_id_veri_9053ad_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationprofile',
            index=models.Index(fields=['created_at'], name='homepage_us_created_ade2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationprofile',
            index=models.Index(fields=['verification_expires_at'], name='homepage_us_verific_d94f51_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationprofile',
            index=models.Index(fields=['is_approved_user'], name='homepage_us_is_appr_6cd481_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationlog',
            index=models.Index(fields=['user_profile', 'action'], name='homepage_us_user_pr_73eb76_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationlog',
            index=models.Index(fields=['created_at'], name='homepage_us_created_ff3974_idx'),
        ),
        migrations.AddIndex(
            model_name='userverificationlog',
            index=models.Index(fields=['result'], name='homepage_us_result_b3079a_idx'),
        ),
    ]
