# Generated by Django 5.2.3 on 2025-07-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home & Kitchen'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
