# Generated by Django 5.2.5 on 2025-08-07 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('city_center', 'Cape Town City Center'), ('camps_bay', 'Camps Bay'), ('sea_point', 'Sea Point'), ('green_point', 'Green Point'), ('woodstock', 'Woodstock'), ('observatory', 'Observatory'), ('rondebosch', 'Rondebosch'), ('claremont', 'Claremont'), ('newlands', 'Newlands'), ('constantia', 'Constantia'), ('hout_bay', 'Hout Bay'), ('muizenberg', 'Muizenberg'), ('fish_hoek', 'Fish Hoek'), ('simons_town', "Simon's Town"), ('bellville', 'Bellville'), ('parow', 'Parow'), ('goodwood', 'Goodwood'), ('athlone', 'Athlone'), ('mitchell_plain', "Mitchell's Plain"), ('khayelitsha', 'Khayelitsha')], default='city_center', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home & Kitchen'), ('sports', 'Sports & Fitness'), ('automotive', 'Automotive'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
